services:
  mysql:
    image: mysql:8.4
    container_name: foodapp-mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: foodpass
      MYSQL_DATABASE: foodapp
    volumes:
      - ./mysql-data:/var/lib/mysql
