version: '3.9'
services:
  mysql:
    image: mysql:8.4
    container_name: foodapp-db
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: foodapp
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
